- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars.yml

  pre_tasks:

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb >= 0

    - name: Ensure br_netfilter is enabled.
      modprobe:
        name: br_netfilter
        state: present

    - name: set iptables
      shell: update-alternatives --set iptables /usr/sbin/iptables-legacy | cat
      ignore_errors: true

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
       name: net.bridge.bridge-nf-call-ip6tables
       value: 1
       state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
       name: net.bridge.bridge-nf-call-iptables
       value: 1
       state: present

    - name: ensure net.ipv4.ip_forward is set to 1
      sysctl:
       name: net.ipv4.ip_forward
       value: 1
       state: present

  roles:
    - geerlingguy.kubernetes

  tasks:
    - name: start kubelet
      service:
         name: kubelet
         state: restarted
      ignore_errors: true

  post_tasks:
    - name: ansible copy file from remote to local.
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{playbook_dir}}/configs/config"
        flat: yes
      when: kubernetes_role == 'control_plane'



